// Auto-generated by inject_version_define.py - DO NOT EDIT
// Source: library.json

#ifndef MAKER_API_VERSION_AUTOGEN_H
#define MAKER_API_VERSION_AUTOGEN_H

#define WEB_MODULE_VERSION_STR "0.1.0"
#define WEB_MODULE_VERSION "0.1.0"

#endif // MAKER_API_VERSION_AUTOGEN_H
