// Auto-generated by inject_version_define.py - DO NOT EDIT
// Source: library.json

#ifndef VERSION_AUTOGEN_H
#define VERSION_AUTOGEN_H

#define WEB_MODULE_VERSION_STR "0.2.0"
#define WEB_MODULE_VERSION "0.2.0"

#endif // VERSION_AUTOGEN_H
