// Auto-generated by inject_version_define.py - DO NOT EDIT
// Source: library.json

#ifndef MAKER_API_VERSION_AUTOGEN_H
#define MAKER_API_VERSION_AUTOGEN_H

#define WEB_MODULE_VERSION_STR "0.2.0" // NOSONAR
#define WEB_MODULE_VERSION "0.2.0" // NOSONAR

#endif // MAKER_API_VERSION_AUTOGEN_H
