name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Python & PlatformIO
      - name: Setup Python & PlatformIO
        run: |
          sudo apt update
          sudo apt install -y gcc g++ make python3-pip lcov unzip wget
          pip3 install platformio

      # 3️⃣ Debug: Show starting directory
      - name: Debug starting directory
        run: |
          echo "PWD = $PWD"
          ls -R .

      # 4️⃣ Setup SonarScanner
      - name: Setup SonarScanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner-cli-5.0.1.3006-linux.zip
          echo "$PWD/sonar-scanner-5.0.1.3006-linux/bin" >> $GITHUB_PATH

      # 5️⃣ Setup Build Wrapper
      - name: Setup Build Wrapper
        run: |
          mkdir -p build-tools
          cd build-tools
          wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          unzip build-wrapper-linux-x86.zip
          chmod +x build-wrapper-linux-x86/build-wrapper-linux-x86-64
          echo "BUILD_WRAPPER_PATH=$PWD/build-wrapper-linux-x86/build-wrapper-linux-x86-64" >> $GITHUB_ENV
          cd $GITHUB_WORKSPACE

      # 6️⃣ Run PlatformIO build & tests with build-wrapper
      - name: Build and test with build-wrapper
        run: |
          mkdir -p bw-output
          echo "Running PlatformIO tests..."
          $BUILD_WRAPPER_PATH --out-dir bw-output pio test -e test_native

      # 7️⃣ Generate C++ coverage data
      - name: Generate coverage data
        run: |
          echo "Generating coverage data..."
          echo "Available .gcno files:"
          find .pio/build/test_native -name "*.gcno" | head -10
          echo "\nFocusing on maker_api .gcno files:"
          find .pio/build/test_native -name "*maker_api*.gcno" -ls

          cd .pio/build/test_native
          echo "\nRunning gcov on all .gcno files..."
          find . -name "*.gcno" -exec gcov -b -l -p -c {} \;
          echo "\nChecking if maker_api .gcov files were created:"
          find . -name "*maker_api*.gcov" -ls
          cd $GITHUB_WORKSPACE

          echo "Generating lcov coverage info..."
          lcov --base-directory . \
               --directory .pio/build/test_native \
               --capture \
               --output-file coverage.info \
               --rc lcov_branch_coverage=1

          echo "Filtering system files..."
          lcov --remove coverage.info '/usr/*' --output-file coverage.info

          echo "Coverage summary:"
          lcov --summary coverage.info

      # 8️⃣ Debug: coverage
      - name: Debug coverage
        run: |
          echo "Coverage data files:"
          ls -l .pio/build/test_native/src/maker_api.* || true
          echo "\nAll .gcov files generated:"
          find . -name "*.gcov" | head -20
          echo "\nSpecifically looking for maker_api gcov files:"
          find . -name "*maker_api*.gcov" -ls || true
          echo "\nTrying to manually generate maker_api gcov:"
          cd .pio/build/test_native/src
          gcov -b -c maker_api.gcda || true
          pwd
          ls -l *maker_api*.gcov || true
          grep -Hn "maker_api" $GITHUB_WORKSPACE/.pio/build/test_native/src/*.gcov | head

      # 9️⃣ Run SonarCloud analysis
      - name: Run SonarCloud analysis
        run: |
          echo "Running sonar-scanner..."
          sonar-scanner \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=andrewmherren \
            -Dsonar.projectKey=andrewmherren_maker_api \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.sources=$GITHUB_WORKSPACE/src,$GITHUB_WORKSPACE/include \
            -Dsonar.tests=$GITHUB_WORKSPACE/test \
            -Dsonar.exclusions=**/build-wrapper-dump.json \
            -Dsonar.coverage.exclusions=**/test/**/* \
            -Dsonar.cfamily.compile-commands=$GITHUB_WORKSPACE/bw-output/compile_commands.json \
            -Dsonar.cfamily.gcov.reportsPath=$GITHUB_WORKSPACE/.pio/build/test_native/src \
            -Dsonar.cpp.file.suffixes=.cpp,.h,.hpp \
            -Dsonar.c.file.suffixes=.c \
            -Dsonar.lang.patterns.cpp=**/*.cpp,**/*.h,**/*.hpp \
            -Dsonar.lang.patterns.c=**/*.c \
            -Dsonar.sourceEncoding=UTF-8 \
            -Dsonar.working.directory=$GITHUB_WORKSPACE/.scannerwork
