name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Python & PlatformIO
      - name: Setup Python & PlatformIO
        run: |
          sudo apt update
          sudo apt install -y gcc g++ make python3-pip lcov unzip wget
          pip3 install platformio

      # 3️⃣ Debug: Show starting directory
      - name: Debug starting directory
        run: |
          echo "PWD = $PWD"
          ls -R .

      # 4️⃣ Setup SonarScanner
      - name: Setup SonarScanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner-cli-5.0.1.3006-linux.zip
          echo "$PWD/sonar-scanner-5.0.1.3006-linux/bin" >> $GITHUB_PATH

      # 5️⃣ Setup Build Wrapper
      - name: Setup Build Wrapper
        run: |
          mkdir -p build-tools
          cd build-tools
          wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          unzip build-wrapper-linux-x86.zip
          chmod +x build-wrapper-linux-x86/build-wrapper-linux-x86-64
          echo "BUILD_WRAPPER_PATH=$PWD/build-wrapper-linux-x86/build-wrapper-linux-x86-64" >> $GITHUB_ENV
          cd $GITHUB_WORKSPACE

      # 6️⃣ Run PlatformIO build & tests with build-wrapper
      - name: Build and test with build-wrapper
        run: |
          mkdir -p bw-output
          echo "Running PlatformIO tests..."
          $BUILD_WRAPPER_PATH --out-dir bw-output pio test -e test_native

      # 7️⃣ Generate C++ coverage data
      - name: Generate coverage data
        run: |
          echo "🔍 Generating coverage data..."

          echo "🧩 Listing .gcno files (first 10):"
          find .pio/build/test_native -name "*.gcno" | head -10

          echo "📂 Running lcov capture..."
          lcov --capture \
               --directory .pio/build/test_native \
               --base-directory $GITHUB_WORKSPACE \
               --output-file coverage.info \
               --rc lcov_branch_coverage=1

          echo "🧹 Filtering out system and test files..."
          # lcov exits 25 when everything filtered out — not fatal
          lcov --remove coverage.info \
               '/usr/*' \
               '*/.pio/libdeps/*' \
               '*/test/*' \
               '*/Unity/*' \
               --output-file coverage.cleaned.info \
               --rc lcov_branch_coverage=1 || true

          echo "📊 Coverage summary (after filtering):"
          lcov --summary coverage.cleaned.info || true

          echo "📦 Moving final coverage report to workspace root..."
          mv coverage.cleaned.info coverage.info || true

          echo "✅ Coverage generation complete. coverage.info ready for SonarCloud."

      # 8️⃣ Upload artifacts
      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gcov-reports
          path: .pio/build/test_native/**/*.gcov

      # 9️⃣ Run SonarCloud analysis
      - name: Run SonarCloud analysis
        run: |
          echo "Running sonar-scanner..."
          sonar-scanner \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=andrewmherren \
            -Dsonar.projectKey=andrewmherren_maker_api \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.sources=$GITHUB_WORKSPACE/src,$GITHUB_WORKSPACE/include \
            -Dsonar.tests=$GITHUB_WORKSPACE/test \
            -Dsonar.exclusions=**/build-wrapper-dump.json \
            -Dsonar.coverage.exclusions=**/test/**/* \
            -Dsonar.cfamily.compile-commands=$GITHUB_WORKSPACE/bw-output/compile_commands.json \
            -Dsonar.cfamily.gcov.reportsPath=$GITHUB_WORKSPACE \
            -Dsonar.cpp.file.suffixes=.cpp,.h,.hpp \
            -Dsonar.c.file.suffixes=.c \
            -Dsonar.lang.patterns.cpp=**/*.cpp,**/*.h,**/*.hpp \
            -Dsonar.lang.patterns.c=**/*.c \
            -Dsonar.sourceEncoding=UTF-8 \
            -Dsonar.working.directory=$GITHUB_WORKSPACE/.scannerwork
