name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Python & PlatformIO
      - name: Setup Python & PlatformIO
        run: |
          sudo apt update
          sudo apt install -y gcc g++ make python3-pip lcov unzip wget gcovr
          pip3 install platformio

      # 3️⃣ Debug: Show starting directory
      - name: Debug starting directory
        run: |
          echo "PWD = $PWD"
          ls -R .

      # 4️⃣ Setup SonarScanner
      - name: Setup SonarScanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner-cli-5.0.1.3006-linux.zip
          echo "$PWD/sonar-scanner-5.0.1.3006-linux/bin" >> $GITHUB_PATH

      # 5️⃣ Setup Build Wrapper
      - name: Setup Build Wrapper
        run: |
          mkdir -p build-tools
          cd build-tools
          wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          unzip build-wrapper-linux-x86.zip
          chmod +x build-wrapper-linux-x86/build-wrapper-linux-x86-64
          echo "BUILD_WRAPPER_PATH=$PWD/build-wrapper-linux-x86/build-wrapper-linux-x86-64" >> $GITHUB_ENV
          cd $GITHUB_WORKSPACE

      # 6️⃣ Run PlatformIO build & tests with build-wrapper
      - name: Build and test with build-wrapper
        run: |
          mkdir -p bw-output
          echo "Running PlatformIO tests..."
          $BUILD_WRAPPER_PATH --out-dir bw-output pio test -e test_native

      # 7️⃣ Generate C++ coverage data
      - name: Generate coverage data
        run: |
          echo "Generating coverage data..."
          ls -l .pio/build/test_native
          find .pio/build/test_native/src -name "*.gcno" -exec gcov -b -l -p -c {} \;

          echo "✅ Coverage generation complete."
          # - name: Generate coverage data
          #   run: |
          #     echo "Generating coverage data..."
          #     cd .pio/build/test_native

          #     # Generate coverage data with gcov while preserving paths and branch info.
          #     # Use a POSIX shell to loop because gcov can produce multiple output files.
          #     find . -type f -name "*.gcno" -print0 | xargs -0 -n1 -P4 sh -c 'gcov --preserve-paths --branch-counts --branch-probabilities "$0"' 

          # Debug: Show what gcov files were created
          echo "=== Generated gcov files ==="
          find . -name "*.gcov" -ls

          # Produce XML report focused on our project sources and excluding system / libdeps
          # --exclude-directories=".*/.pio/.*" \
          gcovr --xml-pretty \
            --filter=".*maker_api.*|.*/src/.*|.*/include/.*" \
            --exclude-directories=".*libdeps.*" \
            --exclude=".*FakeIt.*" \
            --exclude=".*Arduino.*" \
            --exclude=".*unity.*" \
            --exclude="/usr/include/.*" \
            --root $GITHUB_WORKSPACE \
            --object-directory .pio/build/test_native \
            -o coverage.xml \
            --print-summary

          # # Copy coverage XML back to workspace root (sonar-scanner will read this)
          # ls -l coverage.xml
          # cp coverage.xml $GITHUB_WORKSPACE/

          # # Create coverage-reports and copy only relevant gcov files (project files)
          # mkdir -p $GITHUB_WORKSPACE/coverage-reports
          # echo "Copying relevant gcov files..."
          # # Use find + tar pipeline to preserve paths in a portable way and avoid shell exec/|| issues
          # # copy maker_api gcov files
          # find . -name "*maker_api*.gcov" -print0 | tar --null -T - -cf - --no-recursion 2>/dev/null | tar -C $GITHUB_WORKSPACE/coverage-reports -xvf - 2>/dev/null || true
          # # copy src and include gcov files (if present)
          # find ./src -name "*.gcov" -print0 | tar --null -T - -cf - --no-recursion 2>/dev/null | tar -C $GITHUB_WORKSPACE/coverage-reports -xvf - 2>/dev/null || true
          # find ./include -name "*.gcov" -print0 | tar --null -T - -cf - --no-recursion 2>/dev/null | tar -C $GITHUB_WORKSPACE/coverage-reports -xvf - 2>/dev/null || true

          # echo "=== Contents of coverage-reports ==="
          # ls -R $GITHUB_WORKSPACE/coverage-reports || true

          echo "✅ Coverage generation complete."

      # 8️⃣ git checkout main to fix shallow clone issues
      - name: Fix shallow clone for SonarCloud
        run: |
          git fetch --prune --unshallow || true
          git fetch origin +refs/heads/main:refs/remotes/origin/main || true

      # - name: Debug Coverage
      #   run: |
      #     echo "=== Checking coverage files existence ==="
      #     ls -l $GITHUB_WORKSPACE/coverage-reports/

      #     echo "=== Checking coverage file contents ==="
      #     head -n 20 $GITHUB_WORKSPACE/coverage-reports/*.gcov || true

      #     echo "=== Checking coverage XML ==="
      #     head -n 20 $GITHUB_WORKSPACE/coverage.xml || true

      #     echo "=== Checking build wrapper output ==="
      #     ls -l $GITHUB_WORKSPACE/bw-output/

      # 9️⃣ Run SonarCloud analysis
      - name: Run SonarCloud analysis
        run: |
          echo "Running sonar-scanner..."
          # sonar-scanner \
          #   -Dsonar.host.url=https://sonarcloud.io \
          #   -Dsonar.organization=andrewmherren \
          #   -Dsonar.projectKey=andrewmherren_maker_api \
          #   -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
          #   -Dsonar.sources=$GITHUB_WORKSPACE/src,$GITHUB_WORKSPACE/include \
          #   -Dsonar.tests=$GITHUB_WORKSPACE/test \
          #   -Dsonar.exclusions=**/build-wrapper-dump.json \
          #   -Dsonar.coverage.exclusions=**/test/**/* \
          #   -Dsonar.cfamily.compile-commands=$GITHUB_WORKSPACE/bw-output/compile_commands.json \
          #   -Dsonar.cfamily.gcov.reportsPath=$GITHUB_WORKSPACE \
          #   -Dsonar.cfamily.gcov.xmlReportPaths=$GITHUB_WORKSPACE/coverage.xml \
          #   -Dsonar.cpp.file.suffixes=.cpp,.h,.hpp \
          #   -Dsonar.c.file.suffixes=.c \
          #   -Dsonar.lang.patterns.cpp=**/*.cpp,**/*.h,**/*.hpp \
          #   -Dsonar.lang.patterns.c=**/*.c \
          #   -Dsonar.sourceEncoding=UTF-8 \
          #   -Dsonar.working.directory=$GITHUB_WORKSPACE/.scannerwork
          sonar-scanner \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=andrewmherren \
            -Dsonar.projectKey=andrewmherren_maker_api \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.sources=src,include \
            -Dsonar.tests=test \
            -Dsonar.exclusions=**/build-wrapper-dump.json \
            -Dsonar.coverage.exclusions=**/test/**/*,**/libdeps/**/*,**/.pio/**/* \
            -Dsonar.cfamily.build-wrapper-output=bw-output \
            -Dsonar.cfamily.gcov.reportsPath=./pio/build/test_native \
            -Dsonar.cfamily.gcov.xmlReportPaths=coverage.xml \
            -Dsonar.cpp.file.suffixes=.cpp,.h,.hpp \
            -Dsonar.c.file.suffixes=.c \
            -Dsonar.verbose=true \
            -Dsonar.sourceEncoding=UTF-8 \
            -Dsonar.working.directory=.scannerwork
